<?php

namespace ContainerTEdhLp8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B99KLHe.App\Controller\VisiteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B99KLHe.App\\Controller\\VisiteController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'visite' => ['privates', '.errored..service_locator.B99KLHe.App\\Entity\\Visite', NULL, 'Cannot autowire service ".service_locator.B99KLHe": it needs an instance of "App\\Entity\\Visite" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'visite' => 'App\\Entity\\Visite',
        ]))->withContext('App\\Controller\\VisiteController::edit()', $container);
    }
}
