<?php

namespace Container08A2SCk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHbMhGLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iHbMhGL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHbMhGL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.hL0ALtd.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.KRP7HMc.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\EtudiantController::edit' => ['privates', '.service_locator.ADJV2y1.App\\Controller\\EtudiantController::edit()', 'getEtudiantControllereditService', true],
            'App\\Controller\\VisiteController::edit' => ['privates', '.service_locator.B99KLHe.App\\Controller\\VisiteController::edit()', 'getVisiteControllereditService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.hL0ALtd.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.KRP7HMc.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\EtudiantController:edit' => ['privates', '.service_locator.ADJV2y1.App\\Controller\\EtudiantController::edit()', 'getEtudiantControllereditService', true],
            'App\\Controller\\VisiteController:edit' => ['privates', '.service_locator.B99KLHe.App\\Controller\\VisiteController::edit()', 'getVisiteControllereditService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\EtudiantController::edit' => '?',
            'App\\Controller\\VisiteController::edit' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\EtudiantController:edit' => '?',
            'App\\Controller\\VisiteController:edit' => '?',
        ]);
    }
}
