<?php

namespace Container08A2SCk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hL0ALtd.App\Controller\AuthController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hL0ALtd.App\\Controller\\AuthController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tuteurRepository' => ['privates', 'App\\Repository\\TuteurRepository', 'getTuteurRepositoryService', true],
        ], [
            'tuteurRepository' => 'App\\Repository\\TuteurRepository',
        ]))->withContext('App\\Controller\\AuthController::login()', $container);
    }
}
