<?php

namespace Container08A2SCk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KRP7HMc.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KRP7HMc.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tuteurRepository' => ['privates', 'App\\Repository\\TuteurRepository', 'getTuteurRepositoryService', true],
            'etudiantRepository' => ['privates', 'App\\Repository\\EtudiantRepository', 'getEtudiantRepositoryService', true],
            'visiteRepository' => ['privates', 'App\\Repository\\VisiteRepository', 'getVisiteRepositoryService', true],
        ], [
            'tuteurRepository' => 'App\\Repository\\TuteurRepository',
            'etudiantRepository' => 'App\\Repository\\EtudiantRepository',
            'visiteRepository' => 'App\\Repository\\VisiteRepository',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
