<?php

namespace Container08A2SCk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiantControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ADJV2y1.App\Controller\EtudiantController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ADJV2y1.App\\Controller\\EtudiantController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etudiant' => ['privates', '.errored..service_locator.ADJV2y1.App\\Entity\\Etudiant', NULL, 'Cannot autowire service ".service_locator.ADJV2y1": it needs an instance of "App\\Entity\\Etudiant" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'etudiant' => 'App\\Entity\\Etudiant',
        ]))->withContext('App\\Controller\\EtudiantController::edit()', $container);
    }
}
