<?php

namespace Container08A2SCk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B99KLHe.App\Entity\Visite' shared service.
     *
     * @return \App\Entity\Visite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.B99KLHe": it needs an instance of "App\\Entity\\Visite" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
