<?php

namespace Container08A2SCk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VisiteController' shared autowired service.
     *
     * @return \App\Controller\VisiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VisiteController.php';

        $container->services['App\\Controller\\VisiteController'] = $instance = new \App\Controller\VisiteController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\VisiteRepository'] ?? $container->load('getVisiteRepositoryService')), ($container->privates['App\\Repository\\EtudiantRepository'] ?? $container->load('getEtudiantRepositoryService')), ($container->privates['App\\Repository\\TuteurRepository'] ?? $container->load('getTuteurRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\VisiteController', $container));

        return $instance;
    }
}
