<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTEdhLp8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTEdhLp8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTEdhLp8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTEdhLp8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTEdhLp8\App_KernelDevDebugContainer([
    'container.build_hash' => 'TEdhLp8',
    'container.build_id' => '32f91e80',
    'container.build_time' => 1765521848,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTEdhLp8');
