<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App_Entity_Tuteur' => 0,
'Symfony_Component_Security_Core_User_UserInterface' => 1,
'Symfony_Component_Security_Core_User_PasswordAuthenticatedUserInterface' => 2,
'App_Entity_Visite' => 3,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Tuteur',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'prenom' => $o[3],
                    'entreprise' => $o[4],
                    'email' => $o[5],
                    'telephone' => $o[6],
                    'password' => $o[7],
                    'roles' => $o[8],
                    'visites' => $o[9],
                    'etudiants' => $o[10],
                    'userIdentifier' => $o[11],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'nom',
                'prenom',
                'entreprise',
                'email',
                'telephone',
                'password',
                'roles',
                'visites',
                'etudiants',
                'userIdentifier',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            ],
            'attributesMetadata' => [
                [
                    'roles' => $o[1],
                    'userIdentifier' => $o[2],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'roles',
                'userIdentifier',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface',
            ],
            'attributesMetadata' => [
                [
                    'password' => $o[1],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'password',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Visite',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'date' => $o[2],
                    'commentaire' => $o[3],
                    'tuteur' => $o[4],
                    'compteRendu' => $o[5],
                    'statut' => $o[6],
                    'etudiant' => $o[7],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'date',
                'commentaire',
                'tuteur',
                'compteRendu',
                'statut',
                'etudiant',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
